export const COUNTRIES = [
  { code: "CN", key: "china" },
  { code: "US", key: "usa" },
  { code: "DE", key: "germany" },
  { code: "GB", key: "uk" },
  { code: "FR", key: "france" },
  { code: "JP", key: "japan" },
  { code: "KR", key: "korea" },
  { code: "IN", key: "india" },
  { code: "BR", key: "brazil" },
  { code: "RU", key: "russia" },
  { code: "AU", key: "australia" },
  { code: "CA", key: "canada" },
  { code: "IT", key: "italy" },
  { code: "ES", key: "spain" },
  { code: "NL", key: "netherlands" },
  { code: "SG", key: "singapore" },
  { code: "AE", key: "uae" },
  { code: "MX", key: "mexico" },
  { code: "VN", key: "vietnam" },
  { code: "TH", key: "thailand" },
  { code: "MY", key: "malaysia" },
  { code: "ID", key: "indonesia" },
  { code: "TR", key: "turkey" },
  { code: "ZA", key: "southafrica" },
  { code: "OTHER", key: "other" },
]
